#!/usr/bin/env node
'use strict';
const cp=require('child_process'),crypto=require('crypto'),fs=require('fs'),path=require('path');
const ROOT='/home/mathias/dev/tezos/tezos';
const required=new Set(['ocaml_external','camlprim','dune_target','source_mirror','artifact_symbol','rust_c_abi','dune_foreign_archive']);
function die(s){process.stderr.write(`ffi-c-rust: ${s}\n`);process.exit(2)}
function readJson(f){return JSON.parse(fs.readFileSync(f,'utf8'))}
function validate(d){if(d.schema_version!==1||!Array.isArray(d.connectors))throw Error('bad connector envelope');for(const c of d.connectors){if(!c.name||!Number.isInteger(c.version)||!Array.isArray(c.required_witnesses)||!c.required_witnesses.every(x=>required.has(x))||c.required_witnesses.length<2||!c.required_witnesses.includes('artifact_symbol'))throw Error(`unsafe connector ${c.name||''}`)}}
function census(root){return JSON.parse(cp.execFileSync(process.execPath,[path.join(__dirname,'../ffi-boundary-census/census.js'),root],{encoding:'utf8',maxBuffer:64*1024*1024}))}
function symbols(file){const r=cp.spawnSync('nm',['-g','--defined-only',file],{encoding:'utf8',maxBuffer:64*1024*1024});if(r.status!==0)return new Set();return new Set((r.stdout.match(/\b[A-Za-z_][A-Za-z0-9_]*$/gm)||[]))}
function digest(f){return crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex')}
function build(root){const descriptor=readJson(path.join(__dirname,'connectors.json'));validate(descriptor);const artifact=path.join(root,'_build/default/src/rollup_node_rust_deps/liboctez_rollup_node_rust_deps.a');const have=fs.existsSync(artifact)?symbols(artifact):new Set();const rows=census(root).records.filter(r=>r.mechanism==='rust_c_abi'&&r.path.startsWith('src/rustzcash_deps/'));const endpoints=rows.map(r=>{const source=path.join(root,r.path),mirror=path.join(root,'_build/default',r.path),mirrored=fs.existsSync(mirror)&&digest(source)===digest(mirror);const ok=mirrored&&have.has(r.symbol);return {export:r,availability:ok?'RUST_ARCHIVE_ENDPOINT':'MAY_TOP',top_reason:ok?null:(fs.existsSync(artifact)?'no_current_archive_symbol_witness':'no_declared_archive_artifact'),witness:ok?{target:'src/rollup_node_rust_deps/dune:foreign_archives(octez_rollup_node_rust_deps)',source_mirror:path.relative(root,mirror),artifact:path.relative(root,artifact),symbol:r.symbol}:null}});const callbacks=[];for(const file of [...new Set(rows.map(r=>r.path))]){const text=fs.readFileSync(path.join(root,file),'utf8');if(/(?:type\s+\w+\s*=\s*)?(?:unsafe\s+)?extern\s+"C"\s+fn/.test(text))callbacks.push({path:file,availability:'MAY_TOP',top_reason:'callback_receiver_set_not_proved'})}return {schema_version:1,analysis:'ffi_c_rust_callbacks',scope:'Rust archive endpoints and callback frontier only; no OCaml binding, callback edge, ABI claim, graph edge or MUST',connectors:descriptor.connectors,summary:{rust_exports:rows.length,endpoints:endpoints.filter(x=>x.availability==='RUST_ARCHIVE_ENDPOINT').length,callbacks:callbacks.length},endpoints,callbacks}}
const args=process.argv.slice(2);if(args.length!==1||args[0].startsWith('-'))die('usage: c-rust.js <corpus-root>');const root=path.resolve(args[0]);if(!fs.existsSync(root))die('root missing');const x=build(root);x.record_digest=crypto.createHash('sha256').update(JSON.stringify([x.endpoints,x.callbacks])).digest('hex');process.stdout.write(JSON.stringify(x,null,2)+'\n');
